In [3]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

In [5]:
url = 'https://www.scrapethissite.com/pages/simple'

response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

In [8]:
countries=soup.find_all("div", class_ = "country")

In [9]:
countries[0]

<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div>

In [18]:
data = []

for country in countries:
    name = country.find("h3", class_ ="country-name").get_text(strip=True)
    capital = country.find("span", class_="country-capital" ).get_text(strip=True)
    population = country.find("span", class_ = "country-population").get_text(strip=True)
    area = country.find("span", class_ = "country-area").get_text(strip=True)
    data.append([name, capital, population, area])
    print(name, "->",capital, "->", area)

Andorra -> Andorra la Vella -> 468.0
United Arab Emirates -> Abu Dhabi -> 82880.0
Afghanistan -> Kabul -> 647500.0
Antigua and Barbuda -> St. John's -> 443.0
Anguilla -> The Valley -> 102.0
Albania -> Tirana -> 28748.0
Armenia -> Yerevan -> 29800.0
Angola -> Luanda -> 1246700.0
Antarctica -> None -> 1.4E7
Argentina -> Buenos Aires -> 2766890.0
American Samoa -> Pago Pago -> 199.0
Austria -> Vienna -> 83858.0
Australia -> Canberra -> 7686850.0
Aruba -> Oranjestad -> 193.0
Åland -> Mariehamn -> 1580.0
Azerbaijan -> Baku -> 86600.0
Bosnia and Herzegovina -> Sarajevo -> 51129.0
Barbados -> Bridgetown -> 431.0
Bangladesh -> Dhaka -> 144000.0
Belgium -> Brussels -> 30510.0
Burkina Faso -> Ouagadougou -> 274200.0
Bulgaria -> Sofia -> 110910.0
Bahrain -> Manama -> 665.0
Burundi -> Bujumbura -> 27830.0
Benin -> Porto-Novo -> 112620.0
Saint Barthélemy -> Gustavia -> 21.0
Bermuda -> Hamilton -> 53.0
Brunei -> Bandar Seri Begawan -> 5770.0
Bolivia -> Sucre -> 1098580.0
Bonaire -> Kralendijk -> 328.0
Brazil -> Brasília -> 8511965.0
Bahamas -> Nassau -> 13940.0
Bhutan -> Thimphu -> 47000.0
Bouvet Island -> None -> 49.0
Botswana -> Gaborone -> 600370.0
Belarus -> Minsk -> 207600.0
Belize -> Belmopan -> 22966.0
Canada -> Ottawa -> 9984670.0
Cocos [Keeling] Islands -> West Island -> 14.0
Democratic Republic of the Congo -> Kinshasa -> 2345410.0
Central African Republic -> Bangui -> 622984.0
Republic of the Congo -> Brazzaville -> 342000.0
Switzerland -> Bern -> 41290.0
Ivory Coast -> Yamoussoukro -> 322460.0
Cook Islands -> Avarua -> 240.0
Chile -> Santiago -> 756950.0
Cameroon -> Yaoundé -> 475440.0
China -> Beijing -> 9596960.0
Colombia -> Bogotá -> 1138910.0
Costa Rica -> San José -> 51100.0
Cuba -> Havana -> 110860.0
Cape Verde -> Praia -> 4033.0
Curacao -> Willemstad -> 444.0
Christmas Island -> Flying Fish Cove -> 135.0
Cyprus -> Nicosia -> 9250.0
Czech Republic -> Prague -> 78866.0
Germany -> Berlin -> 357021.0
Djibouti -> Djibouti -> 23000.0
Denmark -> Copenhagen -> 43094.0
Dominica -> Roseau -> 754.0
Dominican Republic -> Santo Domingo -> 48730.0
Algeria -> Algiers -> 2381740.0
Ecuador -> Quito -> 283560.0
Estonia -> Tallinn -> 45226.0
Egypt -> Cairo -> 1001450.0
Western Sahara -> Laâyoune / El Aaiún -> 266000.0
Eritrea -> Asmara -> 121320.0
Spain -> Madrid -> 504782.0
Ethiopia -> Addis Ababa -> 1127127.0
Finland -> Helsinki -> 337030.0
Fiji -> Suva -> 18270.0
Falkland Islands -> Stanley -> 12173.0
Micronesia -> Palikir -> 702.0
Faroe Islands -> Tórshavn -> 1399.0
France -> Paris -> 547030.0
Gabon -> Libreville -> 267667.0
United Kingdom -> London -> 244820.0
Grenada -> St. George's -> 344.0
Georgia -> Tbilisi -> 69700.0
French Guiana -> Cayenne -> 91000.0
Guernsey -> St Peter Port -> 78.0
Ghana -> Accra -> 239460.0
Gibraltar -> Gibraltar -> 6.5
Greenland -> Nuuk -> 2166086.0
Gambia -> Bathurst -> 11300.0
Guinea -> Conakry -> 245857.0
Guadeloupe -> Basse-Terre -> 1780.0
Equatorial Guinea -> Malabo -> 28051.0
Greece -> Athens -> 131940.0
South Georgia and the South Sandwich Islands -> Grytviken -> 3903.0
Guatemala -> Guatemala City -> 108890.0
Guam -> Hagåtña -> 549.0
Guinea-Bissau -> Bissau -> 36120.0
Guyana -> Georgetown -> 214970.0
Hong Kong -> Hong Kong -> 1092.0
Heard Island and McDonald Islands -> None -> 412.0
Honduras -> Tegucigalpa -> 112090.0
Croatia -> Zagreb -> 56542.0
Haiti -> Port-au-Prince -> 27750.0
Hungary -> Budapest -> 93030.0
Indonesia -> Jakarta -> 1919440.0
Ireland -> Dublin -> 70280.0
Israel -> None -> 20770.0
Isle of Man -> Douglas -> 572.0
India -> New Delhi -> 3287590.0
British Indian Ocean Territory -> None -> 60.0
Iraq -> Baghdad -> 437072.0
Iran -> Tehran -> 1648000.0
Iceland -> Reykjavik -> 103000.0
Italy -> Rome -> 301230.0
Jersey -> Saint Helier -> 116.0
Jamaica -> Kingston -> 10991.0
Jordan -> Amman -> 92300.0
Japan -> Tokyo -> 377835.0
Kenya -> Nairobi -> 582650.0
Kyrgyzstan -> Bishkek -> 198500.0
Cambodia -> Phnom Penh -> 181040.0
Kiribati -> Tarawa -> 811.0
Comoros -> Moroni -> 2170.0
Saint Kitts and Nevis -> Basseterre -> 261.0
North Korea -> Pyongyang -> 120540.0
South Korea -> Seoul -> 98480.0
Kuwait -> Kuwait City -> 17820.0
Cayman Islands -> George Town -> 262.0
Kazakhstan -> Astana -> 2717300.0
Laos -> Vientiane -> 236800.0
Lebanon -> Beirut -> 10400.0
Saint Lucia -> Castries -> 616.0
Liechtenstein -> Vaduz -> 160.0
Sri Lanka -> Colombo -> 65610.0
Liberia -> Monrovia -> 111370.0
Lesotho -> Maseru -> 30355.0
Lithuania -> Vilnius -> 65200.0
Luxembourg -> Luxembourg -> 2586.0
Latvia -> Riga -> 64589.0
Libya -> Tripoli -> 1759540.0
Morocco -> Rabat -> 446550.0
Monaco -> Monaco -> 1.95
Moldova -> Chişinău -> 33843.0
Montenegro -> Podgorica -> 14026.0
Saint Martin -> Marigot -> 53.0
Madagascar -> Antananarivo -> 587040.0
Marshall Islands -> Majuro -> 181.3
Macedonia -> Skopje -> 25333.0
Mali -> Bamako -> 1240000.0
Myanmar [Burma] -> Naypyitaw -> 678500.0
Mongolia -> Ulan Bator -> 1565000.0
Macao -> Macao -> 254.0
Northern Mariana Islands -> Saipan -> 477.0
Martinique -> Fort-de-France -> 1100.0
Mauritania -> Nouakchott -> 1030700.0
Montserrat -> Plymouth -> 102.0
Malta -> Valletta -> 316.0
Mauritius -> Port Louis -> 2040.0
Maldives -> Malé -> 300.0
Malawi -> Lilongwe -> 118480.0
Mexico -> Mexico City -> 1972550.0
Malaysia -> Kuala Lumpur -> 329750.0
Mozambique -> Maputo -> 801590.0
Namibia -> Windhoek -> 825418.0
New Caledonia -> Noumea -> 19060.0
Niger -> Niamey -> 1267000.0
Norfolk Island -> Kingston -> 34.6
Nigeria -> Abuja -> 923768.0
Nicaragua -> Managua -> 129494.0
Netherlands -> Amsterdam -> 41526.0
Norway -> Oslo -> 324220.0
Nepal -> Kathmandu -> 140800.0
Nauru -> Yaren -> 21.0
Niue -> Alofi -> 260.0
New Zealand -> Wellington -> 268680.0
Oman -> Muscat -> 212460.0
Panama -> Panama City -> 78200.0
Peru -> Lima -> 1285220.0
French Polynesia -> Papeete -> 4167.0
Papua New Guinea -> Port Moresby -> 462840.0
Philippines -> Manila -> 300000.0
Pakistan -> Islamabad -> 803940.0
Poland -> Warsaw -> 312685.0
Saint Pierre and Miquelon -> Saint-Pierre -> 242.0
Pitcairn Islands -> Adamstown -> 47.0
Puerto Rico -> San Juan -> 9104.0
Palestine -> None -> 5970.0
Portugal -> Lisbon -> 92391.0
Palau -> Melekeok -> 458.0
Paraguay -> Asunción -> 406750.0
Qatar -> Doha -> 11437.0
Réunion -> Saint-Denis -> 2517.0
Romania -> Bucharest -> 237500.0
Serbia -> Belgrade -> 88361.0
Russia -> Moscow -> 1.71E7
Rwanda -> Kigali -> 26338.0
Saudi Arabia -> Riyadh -> 1960582.0
Solomon Islands -> Honiara -> 28450.0
Seychelles -> Victoria -> 455.0
Sudan -> Khartoum -> 1861484.0
Sweden -> Stockholm -> 449964.0
Singapore -> Singapore -> 692.7
Saint Helena -> Jamestown -> 410.0
Slovenia -> Ljubljana -> 20273.0
Svalbard and Jan Mayen -> Longyearbyen -> 62049.0
Slovakia -> Bratislava -> 48845.0
Sierra Leone -> Freetown -> 71740.0
San Marino -> San Marino -> 61.2
Senegal -> Dakar -> 196190.0
Somalia -> Mogadishu -> 637657.0
Suriname -> Paramaribo -> 163270.0
South Sudan -> Juba -> 644329.0
São Tomé and Príncipe -> São Tomé -> 1001.0
El Salvador -> San Salvador -> 21040.0
Sint Maarten -> Philipsburg -> 21.0
Syria -> Damascus -> 185180.0
Swaziland -> Mbabane -> 17363.0
Turks and Caicos Islands -> Cockburn Town -> 430.0
Chad -> N'Djamena -> 1284000.0
French Southern Territories -> Port-aux-Français -> 7829.0
Togo -> Lomé -> 56785.0
Thailand -> Bangkok -> 514000.0
Tajikistan -> Dushanbe -> 143100.0
Tokelau -> None -> 10.0
East Timor -> Dili -> 15007.0
Turkmenistan -> Ashgabat -> 488100.0
Tunisia -> Tunis -> 163610.0
Tonga -> Nuku'alofa -> 748.0
Turkey -> Ankara -> 780580.0
Trinidad and Tobago -> Port of Spain -> 5128.0
Tuvalu -> Funafuti -> 26.0
Taiwan -> Taipei -> 35980.0
Tanzania -> Dodoma -> 945087.0
Ukraine -> Kiev -> 603700.0
Uganda -> Kampala -> 236040.0
U.S. Minor Outlying Islands -> None -> 0.0
United States -> Washington -> 9629091.0
Uruguay -> Montevideo -> 176220.0
Uzbekistan -> Tashkent -> 447400.0
Vatican City -> Vatican City -> 0.44
Saint Vincent and the Grenadines -> Kingstown -> 389.0
Venezuela -> Caracas -> 912050.0
British Virgin Islands -> Road Town -> 153.0
U.S. Virgin Islands -> Charlotte Amalie -> 352.0
Vietnam -> Hanoi -> 329560.0
Vanuatu -> Port Vila -> 12200.0
Wallis and Futuna -> Mata-Utu -> 274.0
Samoa -> Apia -> 2944.0
Kosovo -> Pristina -> 10908.0
Yemen -> Sanaa -> 527970.0
Mayotte -> Mamoudzou -> 374.0
South Africa -> Pretoria -> 1219912.0
Zambia -> Lusaka -> 752614.0
Zimbabwe -> Harare -> 390580.0

In [21]:
df = pd.DataFrame(data, columns = ['name', 'capital', 'population', 'area'])
df

                     name           capital population       area
0                 Andorra  Andorra la Vella      84000      468.0
1    United Arab Emirates         Abu Dhabi    4975593    82880.0
2             Afghanistan             Kabul   29121286   647500.0
3     Antigua and Barbuda        St. John's      86754      443.0
4                Anguilla        The Valley      13254      102.0
..                    ...               ...        ...        ...
245                 Yemen             Sanaa   23495361   527970.0
246               Mayotte         Mamoudzou     159042      374.0
247          South Africa          Pretoria   49000000  1219912.0
248                Zambia            Lusaka   13460305   752614.0
249              Zimbabwe            Harare   11651858   390580.0

[250 rows x 4 columns]

In [22]:
df.to_csv("output.csv", index = False)

---
# IMPLEMENTATION OF SENTIMENTAL ANALYSIS

In [1]:
from textblob import TextBlob

In [2]:
text = "I am the best in the world, I am illuminated by god."

In [3]:
blob = TextBlob(text)

In [4]:
polarity = blob.sentiment.polarity
polarity

1.0

In [6]:
subjectivity = blob.sentiment.subjectivity
subjectivity

0.3

In [8]:
print(f"TEXT :: {text} \nPolarity :: {polarity} \nSubjectivity :: {subjectivity}")

TEXT :: I am the best in the world, I am illuminated by god.
Polarity :: 1.0
Subjectivity :: 0.3

In [9]:
if polarity > 0:
    print("Positive statement")
elif polarity < 0:
    print("Negative Statement")
else:
    print("neutral")

Positive statement

---
# DATA IMPLEMENTATION OF TEXT PROCESSING

In [10]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [11]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [17]:
text = "I am surjkumar yadav. !!!! and this is a random text."

In [18]:
# lowercase
text =text.lower()

In [19]:
# remove punctuation
text = re.sub(r'[^\w\s]', '', text)
text

'i am surjkumar yadav  and this is a random text'

In [20]:
# tokenization
words = text.split()
words

['i', 'am', 'surjkumar', 'yadav', 'and', 'this', 'is', 'a', 'random', 'text']

In [22]:
# remove stopwords
stop_words = set(stopwords.words('english'))
filtered = [w for w in words if w not in stop_words]
filtered

['surjkumar', 'yadav', 'random', 'text']

In [23]:
# steeming
ps = PorterStemmer()
stemmed = [ps.stem(w) for w in filtered]
stemmed

['surjkumar', 'yadav', 'random', 'text']

---
# DEMONSTRATE PARSER IN NLP

In [24]:
import spacy
from rich.console import Console
from rich.table import Table

In [25]:
nlp = spacy.load("en_core_web_sm")

In [26]:
sentence = "this is random sentece, I am suraj and cows are grazing under the sun."

In [27]:
doc = nlp(sentence)

In [28]:
console = Console()

In [29]:
table = Table(title="Dependency Parse.")

table.add_column('Token', style= 'cyan', justify = 'center')
table.add_column('Head', style= 'magenta', justify = 'center')
table.add_column('Dependency Tag', style= 'green', justify = 'center')

for token in doc:
    table.add_row(token.text, token.head.text, token.dep_)

console.print(table)

          Dependency Parse.
┏━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━┓
┃  Token  ┃  Head   ┃ Dependency Tag ┃
┡━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━┩
│  this   │   is    │     nsubj      │
│   is    │   am    │     ccomp      │
│ random  │ sentece │      amod      │
│ sentece │   is    │      attr      │
│    ,    │   am    │     punct      │
│    I    │   am    │     nsubj      │
│   am    │   am    │      ROOT      │
│  suraj  │   am    │     acomp      │
│   and   │   am    │       cc       │
│  cows   │ grazing │     nsubj      │
│   are   │ grazing │      aux       │
│ grazing │   am    │      conj      │
│  under  │ grazing │      prep      │
│   the   │   sun   │      det       │
│   sun   │  under  │      pobj      │
│    .    │ grazing │     punct      │
└─────────┴─────────┴────────────────┘

In [30]:
import spacy
from spacy import displacy

In [35]:
npl =  spacy.load('en_core_web_sm')

sentence = "cows are a great animal, all they do is graze and relax."

doc = nlp(sentence)

print(f"{'Token' :<15}{'Dependency':<20}{'Head'}")
print("-"*50)

for token in doc:
    print(f"{token.text:<15}{token.dep_:<20}{token.head.text}")

Token          Dependency          Head
--------------------------------------------------
cows           nsubj               are
are            ccomp               is
a              det                 animal
great          amod                animal
animal         attr                are
,              punct               is
all            nsubj               is
they           nsubj               do
do             relcl               all
is             ROOT                is
graze          acomp               is
and            cc                  is
relax          conj                is
.              punct               is

---
# PERFORM FEATURE EXTRACTION

In [3]:
sentences = [
    "The quick brown fox jumps over the lazy dog.",
    "Artificial intelligence is transforming industries across the world.",
    "She enjoys reading books on quiet Sunday afternoons.",
    "The results of the experiment were both surprising and insightful.",
    "Can you recommend a good restaurant nearby?",
    "After a long day, he likes to relax by listening to classical music.",
    "They traveled to the mountains in search of peace and adventure.",
    "The company launched a new product last week.",
    "Students eagerly prepared for their final exams.",
    "Technology advances at an incredible pace, reshaping society constantly."
]

In [39]:
# bag of words
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X_bow = vectorizer.fit_transform(sentences)

print(vectorizer.get_feature_names_out())
print(X_bow.toarray())

['across' 'advances' 'adventure' 'after' 'afternoons' 'an' 'and'
 'artificial' 'at' 'books' 'both' 'brown' 'by' 'can' 'classical' 'company'
 'constantly' 'day' 'dog' 'eagerly' 'enjoys' 'exams' 'experiment' 'final'
 'for' 'fox' 'good' 'he' 'in' 'incredible' 'industries' 'insightful'
 'intelligence' 'is' 'jumps' 'last' 'launched' 'lazy' 'likes' 'listening'
 'long' 'mountains' 'music' 'nearby' 'new' 'of' 'on' 'over' 'pace' 'peace'
 'prepared' 'product' 'quick' 'quiet' 'reading' 'recommend' 'relax'
 'reshaping' 'restaurant' 'results' 'search' 'she' 'society' 'students'
 'sunday' 'surprising' 'technology' 'the' 'their' 'they' 'to'
 'transforming' 'traveled' 'week' 'were' 'world' 'you']
[[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
  0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0
  0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1
  0 0 0 1 0]
 [0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0
  0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 2 0 0 0 0
  0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
  0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0
  0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0
  1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
  0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0
  0 0 0 0 0]
 [0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0
  0 0 0 0 0]]

In [41]:
# tf-idf vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
x_tfidf = tfidf.fit_transform(sentences)

print(tfidf.get_feature_names_out())
print(x_tfidf.toarray())

['across' 'advances' 'adventure' 'after' 'afternoons' 'an' 'and'
 'artificial' 'at' 'books' 'both' 'brown' 'by' 'can' 'classical' 'company'
 'constantly' 'day' 'dog' 'eagerly' 'enjoys' 'exams' 'experiment' 'final'
 'for' 'fox' 'good' 'he' 'in' 'incredible' 'industries' 'insightful'
 'intelligence' 'is' 'jumps' 'last' 'launched' 'lazy' 'likes' 'listening'
 'long' 'mountains' 'music' 'nearby' 'new' 'of' 'on' 'over' 'pace' 'peace'
 'prepared' 'product' 'quick' 'quiet' 'reading' 'recommend' 'relax'
 'reshaping' 'restaurant' 'results' 'search' 'she' 'society' 'students'
 'sunday' 'surprising' 'technology' 'the' 'their' 'they' 'to'
 'transforming' 'traveled' 'week' 'were' 'world' 'you']
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.34481748
  0.         0.         0.         0.         0.         0.
  0.34481748 0.         0.         0.         0.         0.
  0.         0.34481748 0.         0.         0.         0.
  0.         0.         0.         0.         0.34481748 0.
  0.         0.34481748 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.34481748
  0.         0.         0.         0.         0.34481748 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.40951962 0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]
 [0.36878975 0.         0.         0.         0.         0.
  0.         0.36878975 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.36878975 0.         0.36878975 0.36878975 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.21899504 0.         0.         0.         0.36878975
  0.         0.         0.         0.36878975 0.        ]
 [0.         0.         0.         0.         0.35355339 0.
  0.         0.         0.         0.35355339 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.35355339 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.35355339 0.
  0.         0.         0.         0.         0.         0.35355339
  0.35355339 0.         0.         0.         0.         0.
  0.         0.35355339 0.         0.         0.35355339 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.28566144 0.         0.         0.         0.33603616 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.33603616 0.
  0.         0.         0.         0.         0.         0.
  0.         0.33603616 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.28566144 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.33603616
  0.         0.         0.         0.         0.         0.33603616
  0.         0.39909056 0.         0.         0.         0.
  0.         0.         0.33603616 0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.40824829 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.40824829 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.40824829 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.40824829 0.         0.         0.40824829 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.40824829]
 [0.         0.         0.         0.27852429 0.         0.
  0.         0.         0.         0.         0.         0.
  0.27852429 0.         0.27852429 0.         0.         0.27852429
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.27852429 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.27852429 0.27852429 0.27852429 0.
  0.27852429 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.27852429 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.47354218 0.
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.32409183 0.         0.         0.
  0.27550767 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.32409183 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.32409183
  0.         0.         0.         0.27550767 0.         0.
  0.         0.32409183 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.32409183 0.         0.         0.         0.         0.
  0.         0.19245249 0.         0.32409183 0.27550767 0.
  0.32409183 0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.39675595 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.39675595
  0.39675595 0.         0.         0.         0.         0.
  0.         0.         0.39675595 0.         0.         0.
  0.         0.         0.         0.39675595 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.23560196 0.         0.         0.         0.
  0.         0.39675595 0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.37796447 0.         0.37796447 0.         0.37796447
  0.37796447 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.37796447 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.37796447 0.         0.
  0.         0.         0.37796447 0.         0.         0.
  0.         0.         0.         0.         0.        ]
 [0.         0.33333333 0.         0.         0.         0.33333333
  0.         0.         0.33333333 0.         0.         0.
  0.         0.         0.         0.         0.33333333 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.33333333
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.33333333 0.         0.         0.         0.         0.
  0.         0.         0.         0.33333333 0.         0.
  0.         0.         0.33333333 0.         0.         0.
  0.33333333 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]]

In [43]:
# word embedding
import spacy

nlp = spacy.load("en_core_web_sm")

vectors = []

for doc in sentences:
    doc_vec = nlp(doc).vector
    vectors.append(doc_vec)

print(vectors)

[array([ 0.34989095, -0.40325862, -0.03949225,  0.16969554, -0.3452243 ,
        0.01401486,  0.07222251, -0.13579778,  0.10765314, -0.11415692,
        0.10968002,  0.4599945 ,  0.09269853,  0.02224725, -0.23943481,
        0.19123821, -0.2818126 ,  0.286193  , -0.00636653,  0.03343886,
       -0.28402233,  0.04279877, -0.06942523, -0.43993562,  0.3105947 ,
        0.00279777, -0.08015422, -0.1606426 ,  0.43013072,  0.09410558,
        0.3599847 , -0.43316692, -0.01095172, -0.17716996, -0.30451348,
        0.00641516,  0.08945091,  0.17086755, -0.15653649, -0.04985542,
        0.2116024 ,  0.47726458, -0.1324366 ,  0.10490415,  0.1652211 ,
        0.01230409, -0.16433832,  0.4687388 , -0.05534337,  0.16900519,
        0.17613654,  0.3091825 , -0.08728629, -0.02696779, -0.5518694 ,
        0.68801224, -0.07328683,  0.3394709 , -0.24493253,  0.07419772,
       -0.2868206 , -0.126125  , -0.20082645, -0.5151211 , -0.23869681,
       -0.22120114,  0.26133442, -0.3190369 , -0.23436585, -0.24915504,
        0.0323891 ,  0.20108381,  0.18675742, -0.10150081,  0.04051191,
       -0.41702145, -0.05506469, -0.27437705,  0.28162828, -0.42004356,
       -0.27060407, -0.03928791, -0.27137166,  0.09412998, -0.27039105,
        0.316634  ,  0.5435705 , -0.18425491, -0.21024886,  0.43195015,
       -0.08214601,  0.34302768,  0.57876605,  0.24605985, -0.3294925 ,
       -0.3287037 ], dtype=float32), array([ 1.84276830e-02,  1.27976602e-02, -4.50979024e-02, -1.76440030e-01,
       -1.50474310e-01,  7.03697354e-02,  4.68123436e-01, -5.64512273e-04,
       -1.28568098e-01, -9.39547718e-02,  4.54558656e-02,  1.58819854e-01,
       -2.52891425e-02,  1.65469348e-01, -2.42228583e-01,  4.90654320e-01,
       -5.68372548e-01,  2.92704225e-01,  1.35440245e-01, -1.13583378e-01,
       -7.00715557e-02,  8.14606547e-02, -1.88729972e-01, -1.53315797e-01,
        4.31553483e-01,  8.23754724e-03,  2.63288707e-01,  1.55056089e-01,
        1.73505604e-01,  3.71973038e-01, -3.47631760e-02,  1.61241025e-01,
       -1.23496294e-01, -1.37393340e-01, -3.08529884e-01, -1.65481836e-01,
       -7.15986565e-02,  1.04573555e-01, -2.07296446e-01, -5.45755355e-03,
        3.42870146e-01,  1.66753724e-01, -6.92445040e-03,  1.65505588e-01,
        2.71965384e-01,  2.24850073e-01,  6.35370938e-03,  2.26882324e-01,
        2.52717793e-01, -3.16236228e-01,  2.22277090e-01,  1.18912302e-01,
       -1.39573470e-01, -3.92572999e-01, -3.19115967e-01, -3.64817083e-01,
       -1.40043482e-01, -3.35988998e-02,  3.41217071e-02, -8.40975717e-02,
       -2.69897729e-01,  6.21520691e-02,  7.39602223e-02, -1.57144461e-02,
       -1.78356171e-02,  2.25843668e-01,  2.86494911e-01, -4.52980995e-01,
        5.84402494e-02, -2.02900022e-01, -5.47987595e-02, -6.84265792e-02,
        7.59061202e-02, -4.30282176e-01, -2.30932921e-01, -3.42366219e-01,
       -3.35995108e-01, -5.80959842e-02,  6.09203838e-02, -4.21538681e-01,
       -6.09363578e-02,  5.60342260e-02, -3.74462277e-01,  1.33865606e-02,
       -1.23029090e-02,  1.95954263e-01,  3.50388199e-01, -5.06039336e-02,
       -3.01684499e-01,  6.68886006e-01, -4.60675299e-01,  3.47717285e-01,
        6.17067099e-01,  1.39616430e-01, -3.43808144e-01, -2.81884074e-01],
      dtype=float32), array([ 1.24746695e-01,  2.85847746e-02, -3.30786288e-01, -3.23129117e-01,
        1.40607193e-01, -3.56736183e-02,  7.23645449e-01,  4.96900827e-02,
       -1.16312504e-01, -1.01010494e-01,  1.88214123e-01, -1.11874580e-01,
        5.61198778e-02, -1.01663142e-01, -5.03364392e-02,  1.83515519e-01,
       -4.75231797e-01,  2.68333033e-02,  4.93661344e-01, -3.34990203e-01,
       -3.94936085e-01,  1.00865401e-01, -3.43572408e-01, -1.59059271e-01,
        3.44221979e-01,  3.80622558e-02,  5.83802126e-02,  1.61246464e-01,
        5.37573360e-02,  1.05769262e-01,  2.55679727e-01,  4.67517190e-02,
       -7.28223696e-02,  6.17546588e-02, -4.42916393e-01, -1.46170884e-01,
       -8.71121585e-02,  1.35372475e-01, -2.71336245e-03, -8.84084217e-03,
        3.55945468e-01,  2.80572444e-01, -2.15548679e-01,  2.77825266e-01,
        3.71784896e-01,  4.07456666e-01,  7.12681636e-02,  2.25302801e-01,
       -1.17224455e-03, -4.10999864e-01,  1.53120384e-01, -3.62542272e-01,
       -3.58588286e-02, -7.13225961e-01, -6.24599695e-01, -4.68128137e-02,
       -2.32603386e-01, -3.26519847e-01,  3.09230596e-01,  5.29788397e-02,
       -2.88831651e-01,  1.37124524e-01,  1.11520290e-01, -1.83374807e-01,
        2.11624712e-01,  5.93332529e-01,  3.52620065e-01, -1.13478236e-01,
       -2.67044604e-01,  1.83456745e-02,  2.73965716e-01,  8.57929420e-03,
        1.19331464e-01,  3.99576296e-04,  1.96692407e-01, -1.38706177e-01,
       -4.57094163e-02, -1.04822107e-01, -2.44339198e-01, -2.44899198e-01,
       -1.10761002e-01,  9.17237848e-02, -4.04247761e-01,  1.49834469e-01,
        3.14237666e-03,  3.01154703e-01,  4.42792505e-01, -2.39710972e-01,
       -2.72856504e-01,  1.31830961e-01, -1.62589446e-01, -1.74445640e-02,
        6.38771594e-01,  8.75581130e-02, -3.75127912e-01, -1.08140148e-02],
      dtype=float32), array([ 5.99831164e-01,  5.82000762e-02,  7.96341747e-02, -1.16009898e-01,
        6.08323105e-02, -5.17109782e-02,  1.31297097e-01, -4.19961572e-01,
        2.88561702e-01,  1.05591491e-01, -9.07164738e-02,  1.21891230e-01,
       -8.53519365e-02,  1.48652354e-02, -5.45356050e-02,  2.76706398e-01,
       -2.07955301e-01,  3.39236528e-01, -2.42442593e-01,  1.80374607e-02,
        1.27067700e-01,  1.48943573e-01,  1.29499614e-01, -2.22982153e-01,
        1.73499092e-01, -2.67797619e-01, -6.96601905e-03, -2.86114514e-01,
       -3.66631411e-02,  3.14974338e-01,  2.36574754e-01, -4.05238181e-01,
        5.59665918e-01, -4.14663702e-01,  1.48350894e-01, -2.62227565e-01,
       -1.44489566e-02, -4.87072915e-02,  5.18635707e-03, -1.63458232e-02,
        8.27949420e-02,  1.68741420e-01,  1.95929900e-01, -2.54445672e-01,
        1.30805492e-01,  1.34892082e-02, -2.48524204e-01,  1.52634129e-01,
        7.44364737e-03, -4.02629301e-02,  1.98211193e-01,  1.23555951e-01,
       -3.60922456e-01, -2.02791229e-01, -7.35494122e-02,  8.62590820e-02,
       -3.26177865e-01, -5.79155684e-02, -2.72195250e-01,  1.98304370e-01,
       -2.59958476e-01,  5.06068096e-02, -9.10751373e-02, -4.26663309e-01,
        2.57467330e-01, -4.55184403e-04,  1.39275253e-01, -1.72606334e-01,
        4.78614457e-02, -3.09470475e-01, -8.93057212e-02, -2.12638721e-01,
        1.23100594e-01,  5.55188432e-02, -1.62209161e-02, -3.44982147e-01,
       -3.77710462e-02, -1.90535352e-01,  2.41337016e-01,  2.62102485e-02,
       -3.88456613e-01, -7.94987753e-03, -2.43621066e-01,  5.32054126e-01,
        1.61076427e-01,  5.62317431e-01,  1.10591419e-01,  1.67548001e-01,
       -5.48218377e-02,  1.55382052e-01, -2.08479062e-01, -9.72759053e-02,
        2.77502507e-01,  1.06504345e-02, -3.52220148e-01, -3.00408989e-01],
      dtype=float32), array([-2.32326820e-01, -4.52200830e-01,  2.57852733e-01, -1.82370171e-01,
       -3.73488575e-01,  6.06880337e-02,  2.64051557e-01, -1.24433920e-01,
       -5.10249794e-01,  8.86940658e-02,  1.06024921e-01, -1.42135173e-02,
        9.37876701e-02,  3.21690053e-01, -3.08243185e-01,  2.88952351e-01,
       -8.29949453e-02,  2.91976035e-01,  2.16432139e-01, -4.54260111e-02,
        1.17819034e-01,  4.73188400e-01, -2.69640088e-01, -1.61420375e-01,
        2.92141438e-01,  3.22525799e-01, -1.15811065e-01,  1.60512492e-01,
        2.74141040e-02,  2.49521241e-01,  5.13953984e-01,  2.14056745e-01,
        1.70486122e-02, -1.43576115e-01,  6.07892871e-05, -3.77294123e-01,
        1.01592503e-02, -1.85399666e-01,  2.60971487e-03,  1.04780525e-01,
       -2.02992007e-01,  2.04889655e-01,  1.08150855e-01,  3.48739475e-02,
        4.45456505e-02, -5.60362190e-02, -1.52408615e-01,  3.40758078e-02,
        2.95215040e-01,  1.50561221e-02,  2.98049629e-01, -5.49306944e-02,
        4.29066643e-02, -2.63860613e-01,  1.57773226e-01, -2.22818986e-01,
        1.58555955e-01,  1.82550043e-01, -5.42757511e-02,  3.25440168e-02,
       -2.01686919e-01,  1.12321913e-01, -1.96342558e-01, -3.61952096e-01,
       -2.29506537e-01, -1.13759331e-01,  5.72772861e-01, -3.16578418e-01,
        1.90971419e-02, -1.20023720e-01, -4.23188180e-01,  3.16440016e-01,
       -3.95040989e-01,  1.78637490e-01, -3.72168571e-01,  3.89834225e-01,
       -8.07153061e-03, -1.15827799e-01,  1.21785119e-01, -3.83955240e-01,
       -5.90848327e-02,  1.64285734e-01, -4.83813167e-01, -1.58436820e-02,
       -1.19290553e-01, -1.40274521e-02,  2.47341439e-01,  2.88817376e-01,
       -1.93692595e-02,  3.16813827e-01,  1.65070921e-01, -1.82444841e-01,
        3.73745441e-01, -2.29208261e-01, -1.96763068e-01,  2.75694802e-02],
      dtype=float32), array([-0.05370529, -0.3451363 ,  0.1445786 , -0.01714908, -0.28888342,
       -0.02499576,  0.37108946, -0.17843208,  0.07796182,  0.05301799,
        0.03854055, -0.04656051, -0.28537995, -0.0205458 ,  0.3464876 ,
       -0.07677679, -0.2005261 , -0.09329809,  0.18594787,  0.04878308,
       -0.04563622,  0.10824265, -0.20697321, -0.29261112,  0.09456814,
        0.11895521,  0.23935305,  0.21351136,  0.17817198,  0.16117685,
        0.11872557, -0.23668887,  0.09828658,  0.28959313, -0.21361329,
       -0.09113334,  0.19608454, -0.16294289,  0.05494015, -0.16527918,
        0.17875229,  0.32598117, -0.37699053,  0.07176735,  0.36325073,
       -0.33487976,  0.20459764,  0.09991689,  0.3336038 , -0.15187123,
        0.06982908,  0.01829612,  0.12340461, -0.24920307, -0.13156524,
        0.00067504, -0.15183905, -0.08358649,  0.32309923, -0.15042053,
       -0.36443552, -0.15858811, -0.05175174, -0.2724244 , -0.09597056,
        0.02003508,  0.23973939, -0.36653396, -0.107828  ,  0.31135836,
       -0.02095392,  0.05279895, -0.0498737 , -0.00944869, -0.12434755,
       -0.00317402, -0.26602218,  0.06349044,  0.04508131, -0.03201767,
       -0.07120407,  0.14167927, -0.19096994, -0.04256865,  0.00858893,
        0.07656291,  0.4064183 ,  0.11135944,  0.01217252,  0.3959419 ,
       -0.11635205,  0.08298977,  0.28472015,  0.1319593 , -0.62891537,
       -0.10043868], dtype=float32), array([ 0.05106072,  0.01165129, -0.4131802 , -0.12742601,  0.06549911,
        0.02912769,  0.559865  ,  0.2656455 ,  0.1466522 ,  0.07648139,
        0.08071736,  0.00285561, -0.16097099, -0.15814833,  0.51022553,
        0.20568947, -0.23479228,  0.28834805,  0.27247074,  0.49740514,
       -0.05678828,  0.00277032,  0.15129639, -0.38602778,  0.40253487,
       -0.10264329,  0.26054022, -0.3786235 ,  0.05987502, -0.05406551,
       -0.34208515, -0.07184198,  0.31177077, -0.17947386, -0.29015777,
        0.05436822,  0.16435815,  0.04428313,  0.1144411 ,  0.3244271 ,
        0.02223111,  0.14442801,  0.01012254, -0.00233917,  0.06525798,
        0.05976794, -0.22061138,  0.08493768,  0.25428948, -0.11360241,
       -0.00635533, -0.37744737, -0.08386178, -0.360322  , -0.1101776 ,
       -0.35502934, -0.40576398, -0.08859233,  0.05328717, -0.04965631,
       -0.2235202 , -0.37589255, -0.02950936, -0.2291941 , -0.0394231 ,
       -0.00644156, -0.09064025,  0.01250445, -0.19501944,  0.0416558 ,
       -0.3363767 , -0.33572975, -0.01350507, -0.38670588, -0.1995102 ,
       -0.2782481 , -0.04341212, -0.01953495,  0.02370956, -0.09272458,
        0.00667945, -0.14368849, -0.24421443,  0.4769833 ,  0.8128915 ,
        0.31937057, -0.02921306,  0.39784756, -0.30468088,  0.45984712,
       -0.16758335,  0.19000156,  0.39887333,  0.00418845, -0.4653996 ,
       -0.05901822], dtype=float32), array([ 0.42875323, -0.19856301, -0.24999581, -0.13779798, -0.38767138,
        0.16744234,  0.4636067 , -0.04455968, -0.26712108, -0.2673325 ,
       -0.14680307,  0.4916805 ,  0.10623088,  0.41170844, -0.2777346 ,
        0.2917477 , -0.40619284,  0.01495282,  0.34683385,  0.13453528,
        0.00162518,  0.27932268,  0.01694697, -0.4728301 ,  0.36170495,
       -0.06987011,  0.01153248, -0.24254887,  0.32871962,  0.33194545,
        0.41861314, -0.08983088, -0.1283926 , -0.11281698, -0.34578335,
       -0.37594432, -0.41286817,  0.24321002, -0.17632098,  0.06590194,
        0.1910216 ,  0.84815145, -0.09483792,  0.18580921, -0.05950035,
       -0.11715325, -0.26304045,  0.5628015 ,  0.3056324 ,  0.06222259,
        0.06675604,  0.06429663,  0.30294624, -0.3571193 ,  0.26435548,
        0.05622135,  0.17971307, -0.11280148,  0.0220323 , -0.07530486,
       -0.4267443 , -0.11329416, -0.16219133, -0.4516236 ,  0.27446267,
       -0.31893453, -0.08156279, -0.7026193 , -0.3654305 , -0.5948208 ,
        0.06309525,  0.41495484, -0.18881512, -0.40592125, -0.24996302,
       -0.28665036, -0.32017502,  0.10666498,  0.3017259 , -0.18415417,
       -0.155326  , -0.27150267, -0.4138312 ,  0.44905937, -0.20578137,
        0.2024443 ,  1.061533  , -0.05397397, -0.18455523,  0.3000058 ,
       -0.0665934 ,  0.05712334,  0.42445946, -0.01768781, -0.11878207,
       -0.32399777], dtype=float32), array([ 0.25148773,  0.00851259, -0.4529971 , -0.43888482,  0.17533794,
       -0.08878653,  0.6191005 , -0.03087217, -0.22574455, -0.02722409,
        0.10056883,  0.36073455, -0.13343745,  0.18855084, -0.5249773 ,
        0.01512782, -0.03105875,  0.28108275,  0.00409788,  0.2736288 ,
       -0.07632129, -0.3137086 , -0.18072179, -0.3089694 ,  0.5014315 ,
       -0.09737122,  0.03667113, -0.17750183,  0.1262701 ,  0.05951088,
        0.49620262, -0.0535201 ,  0.44986886, -0.32399395, -0.23120123,
       -0.10863146,  0.01191913,  0.07156143,  0.08528936, -0.1322839 ,
       -0.09266895,  0.0028514 , -0.21842179, -0.07753227,  0.16654065,
       -0.18195269, -0.02478263,  0.11189033,  0.03052876, -0.10925655,
        0.18955487,  0.07653111, -0.20571709, -0.5510714 , -0.3943146 ,
        0.56213033,  0.21213277, -0.2216265 ,  0.14947347,  0.01413482,
       -0.16990583, -0.39651263, -0.02726649, -0.42310005,  0.3628798 ,
        0.22321433,  0.04880659, -0.46085268,  0.03489275,  0.02632287,
        0.20956881, -0.03964143, -0.41318744, -0.04504351, -0.1730828 ,
        0.25303528, -0.16602185,  0.11795413,  0.02621131,  0.00335208,
       -0.14765523,  0.04990295, -0.18216448,  0.39822778, -0.03195599,
        0.08830796,  0.64586794,  0.29441413,  0.04712863, -0.08464918,
        0.0581832 , -0.04419061,  0.78094983, -0.018748  , -0.20164025,
       -0.44259256], dtype=float32), array([ 7.65914284e-03,  4.70017530e-02, -1.75615717e-02, -1.28505126e-01,
        6.97684959e-02,  4.25932527e-01,  2.80391097e-01,  5.44533692e-03,
       -1.83124430e-04,  6.03452474e-02,  5.62865101e-02, -2.16360956e-01,
       -4.10978884e-01,  1.50723144e-01,  2.88124353e-01,  3.38066608e-01,
       -3.25473905e-01, -1.03869013e-01, -5.39807640e-02,  7.91471004e-02,
       -1.14504941e-01,  3.07831168e-01, -2.55377978e-01, -4.31321889e-01,
        2.41940748e-02,  2.76065469e-01,  2.29253341e-02,  8.91485512e-02,
        3.84658724e-01,  3.62648745e-03,  5.64166009e-01,  1.13850385e-01,
       -5.50397635e-02, -8.32843035e-02, -2.36487299e-01, -1.77267492e-01,
       -2.06903562e-01, -5.45897111e-02,  2.20345408e-01, -3.07896852e-01,
       -4.66325395e-02,  3.31948072e-01, -9.62859690e-02, -1.05733819e-01,
        5.92161380e-02,  6.92149773e-02, -2.41358131e-01,  1.98853210e-01,
        4.39614952e-01, -1.84004307e-02,  4.00390536e-01, -2.03050002e-01,
       -5.06519713e-03, -1.67882323e-01,  9.64159667e-02, -1.98542014e-01,
       -1.39629096e-01,  4.28232811e-02,  1.69469967e-01, -5.50782345e-02,
       -3.31428707e-01, -2.02224061e-01, -3.47084641e-01, -1.83902979e-01,
       -4.99889813e-02,  2.28145018e-01,  2.39406675e-01, -4.43469226e-01,
       -2.46639863e-01, -2.81412870e-01,  2.18325518e-02,  1.55454986e-02,
        1.94116816e-01, -2.72441506e-02, -1.12361617e-01, -2.31765881e-01,
        1.77608386e-01, -9.03364718e-02,  1.26571998e-01, -3.33815873e-01,
       -3.72362018e-01, -4.50402778e-03, -1.52790606e-01, -2.96862349e-02,
       -1.63285345e-01,  3.09757799e-01,  5.01512349e-01, -1.18088182e-02,
       -8.26522559e-02,  4.76190448e-01, -1.40225589e-01,  5.67747802e-02,
        5.14599741e-01,  1.77257016e-01, -5.82864165e-01, -1.78896174e-01],
      dtype=float32)]

---
#  One Hot Encoding

In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [15]:
sentences

['The quick brown fox jumps over the lazy dog.',
 'Artificial intelligence is transforming industries across the world.',
 'She enjoys reading books on quiet Sunday afternoons.',
 'The results of the experiment were both surprising and insightful.',
 'Can you recommend a good restaurant nearby?',
 'After a long day, he likes to relax by listening to classical music.',
 'They traveled to the mountains in search of peace and adventure.',
 'The company launched a new product last week.',
 'Students eagerly prepared for their final exams.',
 'Technology advances at an incredible pace, reshaping society constantly.']

In [16]:
words = [word for sentence in sentences for word in sentence.split() ]

In [23]:
vocab = sorted(set(words))
vocab_array = np.array(vocab).reshape(-1, 1)

In [24]:
encoder = OneHotEncoder(sparse_output = False)

In [25]:
one_hot_vectors = encoder.fit_transform(vocab_array)

In [26]:
max_len = max(len(word) for word in vocab)
for word, vector in zip(vocab, one_hot_vectors):
    print(f"{word:<{max_len}} --> {vector.astype(int)}")

After        --> [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
Artificial   --> [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
Can          --> [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
She          --> [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
Students     --> [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
Sunday       --> [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
Technology   --> [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
The          --> [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
They         --> [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
a            --> [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
across       --> [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
advances     --> [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
adventure.   --> [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
afternoons.  --> [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
an           --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
and          --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
at           --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
books        --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
both         --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
brown        --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
by           --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
classical    --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
company      --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
constantly.  --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
day,         --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
dog.         --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
eagerly      --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
enjoys       --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
exams.       --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
experiment   --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
final        --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
for          --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
fox          --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
good         --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
he           --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
in           --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
incredible   --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
industries   --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
insightful.  --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
intelligence --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
is           --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
jumps        --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
last         --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
launched     --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
lazy         --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
likes        --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
listening    --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
long         --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
mountains    --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
music.       --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
nearby?      --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
new          --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
of           --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
on           --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
over         --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
pace,        --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
peace        --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
prepared     --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
product      --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
quick        --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
quiet        --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
reading      --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
recommend    --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
relax        --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
reshaping    --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
restaurant   --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0]
results      --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0]
search       --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0]
society      --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0]
surprising   --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0]
the          --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0]
their        --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0]
to           --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0]
transforming --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0]
traveled     --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0]
week.        --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0]
were         --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0]
world.       --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0]
you          --> [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1]

---
# BAG OF WORDS

In [27]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string
import pandas as pd

In [28]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [29]:
corpus = [
    "I enjoy machine learning.",
    "AI is powerful.",
    "I love deep learning."
]

In [30]:
def pre_process(text):
    text = text.lower()
    text = text.translate(str.maketrans("", "", string.punctuation))
    tokens = word_tokenize(text)
    return tokens

In [31]:
processed_corpus = [pre_process(sentence) for sentence in corpus]

In [32]:
vocabulary = sorted(set(word for sentence in processed_corpus for word in sentence))
print(vocabulary)
print(len(vocabulary))

['ai', 'deep', 'enjoy', 'i', 'is', 'learning', 'love', 'machine', 'powerful']
9

In [34]:
def create_bow_vector(sentence, vocab):
    vector = [0] * len(vocab)
    for word in sentence:
        if word in vocab:
            idx = vocab.index(word)
            vector[idx] += 1
    return vector

In [35]:
bow_vectors = [create_bow_vector(sentence, vocabulary) for sentence in processed_corpus]

In [36]:
bow_vectors

[[0, 0, 1, 1, 0, 1, 0, 1, 0],
 [1, 0, 0, 0, 1, 0, 0, 0, 1],
 [0, 1, 0, 1, 0, 1, 1, 0, 0]]

In [37]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string
import pandas as pd

# Download NLTK tokenizer package (run once)
nltk.download('punkt')

# Sample Corpus
corpus = [
    "Python is amazing and fun.",
    "Python is not just fun but also powerful.",
    "Learning Python is fun!",
]

# Preprocessing Function
def preprocess(text):
    # Lowercase
    text = text.lower()
    # Remove punctuation
    text = text.translate(str.maketrans("", "", string.punctuation))
    # Tokenize into words
    tokens = word_tokenize(text)
    return tokens

# Process the corpus
processed_corpus = [preprocess(sentence) for sentence in corpus]

# Build vocabulary (unique words across corpus)
vocabulary = sorted(set(word for sentence in processed_corpus for word in sentence))
print("Vocabulary:", vocabulary)
print("Vocabulary size:", len(vocabulary))

# Function to create BoW vector for a sentence
def create_bow_vector(sentence, vocab):
    vector = [0] * len(vocab)
    for word in sentence:
        if word in vocab:
            idx = vocab.index(word)
            vector[idx] += 1
    return vector

# Create BoW vectors for all sentences
bow_vectors = [create_bow_vector(sentence, vocabulary) for sentence in processed_corpus]

# Print BoW vectors
print("Bag of Words Vectors:")
for vector in bow_vectors:
    print(vector)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

Vocabulary: ['also', 'amazing', 'and', 'but', 'fun', 'is', 'just', 'learning', 'not', 'powerful', 'python']
Vocabulary size: 11
Bag of Words Vectors:
[0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1]
[1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1]
[0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1]

----
# NGRAMS

An n-gram is a sequence of “n” items (usually words or characters) from a given text.

Unigram = 1 word sequence (e.g., “hello”, “world”)

Bigram = 2 word sequence (e.g., “hello world”)

Trigram = 3 word sequence (e.g., “the quick brown”)

N-grams are used in language modeling, text analysis, and many NLP tasks. They capture word patterns and context better than using single words alone.

In [38]:
import pandas as pd
import nltk
from nltk.util import ngrams
from nltk.corpus import reuters
from nltk import trigrams
from collections import defaultdict

nltk.download("punkt")
nltk.download("reuters")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package reuters to /root/nltk_data...

True

In [39]:
df = pd.DataFrame({
    "word": ["apple", "banana", "cherry", "date"],
    "POS": ["pronoun", "verb", "noun", "adverb"]
})

In [41]:

df

     word      POS
0   apple  pronoun
1  banana     verb
2  cherry     noun
3    date   adverb

In [40]:
one_hot = pd.get_dummies(df["word"], prefix="token")
print(one_hot)

   token_apple  token_banana  token_cherry  token_date
0         True         False         False       False
1        False          True         False       False
2        False         False          True       False
3        False         False         False        True

In [42]:
def generate_ngrams(tokens, n):
    return [tokens[i:i+n] for i in range(len(tokens)-n+1)]

In [43]:
sentence = "I love Python programming".split()
print(generate_ngrams(sentence, 1))   # Unigrams
print(generate_ngrams(sentence, 2))   # Bigrams
print(generate_ngrams(sentence, 3))   # Trigrams

[['I'], ['love'], ['Python'], ['programming']]
[['I', 'love'], ['love', 'Python'], ['Python', 'programming']]
[['I', 'love', 'Python'], ['love', 'Python', 'programming']]

In [44]:
words = [w.lower() for w in reuters.words() if w.isalpha()]
tri_grams = list(trigrams(words))

model = defaultdict(lambda: defaultdict(lambda: 0))
for w1, w2, w3 in tri_grams:
    model[(w1, w2)][w3] += 1
# Calculate probabilities
for w1_w2 in model:
    total = float(sum(model[w1_w2].values()))
    for w3 in model[w1_w2]:
        model[w1_w2][w3] /= total

In [45]:
def predict_next_word(w1, w2):
    next_word_probs = model[w1, w2]
    if next_word_probs:
        return max(next_word_probs, key=next_word_probs.get)
    return "No prediction available"

print(predict_next_word("the", "market"))

is

In [47]:
data = {
    "id": [1, 2, 3],
    "text": [
        "I love natural language processing",
        "Natural language processing is fun",
        "I love deep learning"
    ]
}
df = pd.DataFrame(data)

def create_ngrams(text, n):
    tokens = text.lower().split()
    return list(ngrams(tokens, n))

df["bigrams"] = df["text"].apply(lambda x: create_ngrams(x, 2))
df["trigrams"] = df["text"].apply(lambda x: create_ngrams(x, 3))

df[["text", "bigrams", "trigrams"]]

,text,bigrams,trigrams
0,I love natural language processing,"[(i, love), (love, natural), (natural, languag...","[(i, love, natural), (love, natural, language)..."
1,Natural language processing is fun,"[(natural, language), (language, processing), ...","[(natural, language, processing), (language, p..."
2,I love deep learning,"[(i, love), (love, deep), (deep, learning)]","[(i, love, deep), (love, deep, learning)]"

---
# TF-IDF -->  Term Frequency - Inverse Document Frequency

TF-IDF is used to convert text documents into numeric feature vectors that give higher scores to words that are unique or rare in a document but not common everywhere. This helps in many NLP tasks like classification or clustering.

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [51]:
documents = [
    "The cat sat on the mat.",
    "The dog sat on the log.",
    "The cat chased the mouse.",
    "The dog barked at the cat.",
    "Cats and dogs are common pets."
]

In [52]:
vectorizer = TfidfVectorizer(stop_words='english')

In [53]:
tfidf_matrix = vectorizer.fit_transform(documents)

In [54]:
df_tfidf = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())
df_tfidf

,barked,cat,cats,chased,common,dog,dogs,log,mat,mouse,pets,sat
0,0.000000,0.462208,0.0,0.00000,0.0,0.000000,0.0,0.000000,0.690159,0.00000,0.0,0.556816
1,0.000000,0.000000,0.0,0.00000,0.0,0.531772,0.0,0.659118,0.000000,0.00000,0.0,0.531772
2,0.000000,0.427993,0.0,0.63907,0.0,0.000000,0.0,0.000000,0.000000,0.63907,0.0,0.000000
3,0.690159,0.462208,0.0,0.00000,0.0,0.556816,0.0,0.000000,0.000000,0.00000,0.0,0.000000
4,0.000000,0.000000,0.5,0.00000,0.5,0.000000,0.5,0.000000,0.000000,0.00000,0.5,0.000000

---
# Word embeddings
Word embeddings are dense, multi-dimensional numeric representations of words.
They are learned from real text so that words with similar meaning or use have similar vector values (positions in the multi-dimensional space).
Unlike one-hot encoding or Bag of Words, word embeddings capture semantic meaning and the relationships between words, making them very useful for machine learning and NLP applications.
Semantic meaning: Capture similarity of words (“dog” and “cat” are closer than “dog” and “mat”).

Reduces dimensionality: Each word is a compact vector, not a huge sparse array.

Input for deep learning: Vectors can be fed into complex models for sentiment analysis, translation, etc.

In [56]:
pip install gensim

Collecting gensim
  Downloading gensim-4.3.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
Collecting numpy<2.0,>=1.18.5 (from gensim)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 1.9 MB/s eta 0:00:00
Collecting scipy<1.14.0,>=1.7.0 (from gensim)
  Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.3.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=1.8.1->gensim) (1.17.3)
Downloading gensim-4.3.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.6/26.6 MB 32.4 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 57.1 MB/s eta 0:00:00
Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 14.8 MB/s eta 0:00:00
Installing collected packages: numpy, scipy, gensim
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.1
    Uninstalling scipy-1.16.1:
      Successfully uninstalled scipy-1.16.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tsfresh 0.21.1 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
Successfully installed gensim-4.3.3 numpy-1.26.4 scipy-1.13.1

In [1]:
from gensim.models import Word2Vec

sentences = [
    ['the', 'cat', 'sat', 'on', 'the', 'mat'],
    ['the', 'dog', 'sat', 'on', 'the', 'rug'],
    ['the', 'cat', 'chased', 'the', 'mouse'],
    ['the', 'dog', 'barked', 'at', 'the', 'cat']
]

model = Word2Vec(sentences, vector_size=50, window=3, min_count=1, sg=1)

In [2]:
vector_cat = model.wv['cat']
print("Vector for 'cat':\n", vector_cat)

Vector for 'cat':
 [-0.01631589  0.00899154 -0.00827435  0.00164885  0.01699699 -0.00892466
  0.00903494 -0.013574   -0.00709726  0.01879679 -0.00315515  0.00064249
 -0.00828101 -0.01536522 -0.00301625  0.00494004 -0.00177567  0.01106763
 -0.00548626  0.00452034  0.01091177  0.01669204 -0.00290721 -0.01841634
  0.00874107  0.00114392  0.01488411 -0.00162636 -0.00527696 -0.01750593
 -0.00171294  0.00565275  0.01080254  0.01410523 -0.01140614  0.00371746
  0.01217764 -0.0095963  -0.00621408  0.01359538  0.00326288  0.00037996
  0.0069475   0.00043539  0.01923791  0.01012151 -0.01783448 -0.01408312
  0.00180324  0.01278482]

In [3]:
similar_to_cat = model.wv.most_similar('cat', topn=7)
for word, score in similar_to_cat:
    print(f"word: {word}, score: {score:.4f}")

word: sat, score: 0.1249
word: barked, score: 0.0740
word: the, score: 0.0424
word: at, score: 0.0183
word: dog, score: 0.0111
word: rug, score: 0.0014
word: chased, score: -0.1191